{% set name = "TensorWaves" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 23e85ddff979f32c0d2493094d595d822655a28b2fd7eaad9948a5d68f9a4f8c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - setuptools_scm
  run:
    - python >=3.6,<3.10
    - attrs >=20.1.0
    - iminuit >=2.0
    - numpy
    - PyYAML >=5.1
    - sympy >=1.9
    - tqdm >=4.24.0

test:
  imports:
    - tensorwaves
    - tensorwaves.data
    - tensorwaves.estimator
    - tensorwaves.function
    - tensorwaves.interface
    - tensorwaves.optimizer

about:
  home: https://github.com/ComPWA/tensorwaves
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python fitter package for multiple computational back-ends

  description: |
    TensorWaves is a fitter package that optimizes mathematical models to data
    samples. The models can be any _symbolic_ mathematical expression that is then
    converted to any computational backend. In addition, TensorWaves provides
    functionality to generate toy Monte Carlo data samples. The package is
    developed in parallel with [AmpForm](https://github.com/ComPWA/ampform), which
    implements physics models, but its 'lambdifying' mechanisms can in principle be
    used independently.

    All documentation can be found on
    [tensorwaves.rtfd.io](https://tensorwaves.readthedocs.io).

  dev_url: https://github.com/ComPWA/tensorwaves
  doc_url: https://tensorwaves.readthedocs.io

extra:
  recipe-maintainers:
    - redeboer
