{% set name = "TensorWaves" %}
{% set version = "0.4.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: dc81b4849373ef94ee2e73ccda5769c56a3a617f8887d3dcb5be57c568f7d805

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - attrs >=20.1.0
    - iminuit >=2.0
    - numpy
    - PyYAML >=5.1
    - sympy >=1.9
    - tqdm >=4.24.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - tensorwaves
    - tensorwaves.data
    - tensorwaves.estimator
    - tensorwaves.function
    - tensorwaves.interface
    - tensorwaves.optimizer

about:
  description: |
    TensorWaves is a fitter package that optimizes mathematical models to data
    samples. The models can be any _symbolic_ mathematical expression that is then
    converted to any computational backend. In addition, TensorWaves provides
    functionality to generate toy Monte Carlo data samples. The package is
    developed in parallel with [AmpForm](https://github.com/ComPWA/ampform), which
    implements physics models, but its 'lambdifying' mechanisms can in principle be
    used independently.

    All documentation can be found on
    [tensorwaves.rtfd.io](https://tensorwaves.readthedocs.io).
  dev_url: https://github.com/ComPWA/tensorwaves
  doc_url: https://tensorwaves.readthedocs.io
  home: https://github.com/ComPWA/tensorwaves
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python fitter package for multiple computational back-ends


extra:
  recipe-maintainers:
    - redeboer
    - Zeyna777
